name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm build

#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Setup Node 16.x
#        uses: actions/setup-node@v3
#        with:
#          node-version: 16.x
#          cache: yarn
#      - run: yarn install
#      - run: yarn run test
#
#  test-e2e:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Setup Node 16.x
#        uses: actions/setup-node@v3
#        with:
#          node-version: 16.x
#          cache: yarn
#      - run: yarn install
#      - run: yarn run test:e2e
